In [1]:
import numpy as numpy
import pandas as pd

In [4]:
df=pd.read_csv('countries.csv')
df

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.000000,65.000000,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.000000,20.000000,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.000000,3.000000,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.500000,1.500000,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.500000,18.500000,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,Vietnam,Socialist Republic of Vietnam,Vietnamese dong,Hanoi,South-Eastern Asia,Asia,Vietnamese,16.166667,107.833333,123600.0,...,98186856,30.26050,60123739,38063117,1.04,3.08,Authoritarian,28.4,Nguyễn Phú Trọng,General Secretary of the Communist Party
190,West Bank and Gaza,West Bank and Gaza,Israeli new shekel,Ramallah,Western Asia,Asia,Palestinian,31.900000,35.200000,4449.0,...,5043612,NaN,1145354,3898258,1.75,4.39,Hybrid regime,15.4,NaN,NaN
191,Yemen,Republic of Yemen,Yemeni rial,Sana'a,Western Asia,Asia,Yemeni,15.000000,48.000000,234520.0,...,33696614,0.00000,20491585,13205029,1.27,1.95,Authoritarian,14.8,Abdrabbuh Mansur Hadi,President
192,Zambia,Republic of Zambia,New Zambian kwacha,Lusaka,Eastern Africa,Africa,Zambian,-15.000000,30.000000,238360.0,...,20017675,15.06020,10857387,9160288,2.15,5.61,Hybrid regime,13.2,Edgar Lungu,President
193,Zimbabwe,Republic of Zimbabwe,U.S. dollar,Harare,Eastern Africa,Africa,Zimbabwean,-20.000000,30.000000,162000.0,...,16320537,30.56600,11033499,5287038,1.85,3.16,Authoritarian,14.2,Emmerson Mnangagwa,President

In [5]:
df.shape

(194, 64)

df.info()

In [8]:
df.describe

<bound method NDFrame.describe of                 country                             country_long  \
0           Afghanistan             Islamic State of Afghanistan
1               Albania                      Republic of Albania
2               Algeria  People's Democratic Republic of Algeria
3               Andorra                  Principality of Andorra
4                Angola              People's Republic of Angola
..                  ...                                      ...
189             Vietnam            Socialist Republic of Vietnam
190  West Bank and Gaza                       West Bank and Gaza
191               Yemen                        Republic of Yemen
192              Zambia                       Republic of Zambia
193            Zimbabwe                     Republic of Zimbabwe

               currency      capital_city              region continent  \
0        Afghan afghani             Kabul       Southern Asia      Asia
1          Albanian lek            Tirana     Southern Europe    Europe
2        Algerian dinar           Algiers     Northern Africa    Africa
3                  Euro  Andorra la Vella     Southern Europe    Europe
4        Angolan kwanza            Luanda       Middle Africa    Africa
..                  ...               ...                 ...       ...
189     Vietnamese dong             Hanoi  South-Eastern Asia      Asia
190  Israeli new shekel          Ramallah        Western Asia      Asia
191         Yemeni rial            Sana'a        Western Asia      Asia
192  New Zambian kwacha            Lusaka      Eastern Africa    Africa
193         U.S. dollar            Harare      Eastern Africa    Africa

         demonym   latitude   longitude  agricultural_land  ...  population  \
0         Afghan  33.000000   65.000000           383560.0  ...    41128771
1       Albanian  41.000000   20.000000            11655.5  ...     2775634
2       Algerian  28.000000    3.000000           413588.0  ...    44903225
3       Andorran  42.500000    1.500000              187.2  ...       79824
4        Angolan -12.500000   18.500000           569525.0  ...    35588987
..           ...        ...         ...                ...  ...         ...
189   Vietnamese  16.166667  107.833333           123600.0  ...    98186856
190  Palestinian  31.900000   35.200000             4449.0  ...     5043612
191       Yemeni  15.000000   48.000000           234520.0  ...    33696614
192      Zambian -15.000000   30.000000           238360.0  ...    20017675
193   Zimbabwean -20.000000   30.000000           162000.0  ...    16320537

     women_parliament_seats_pct  rural_population  urban_population  press  \
0                      27.01610          30181937          10946834   2.14
1                      35.71430           1004807           1770827   2.62
2                       8.10811          11328186          33575039   1.71
3                      46.42860              9730             70094   3.17
4                      33.63640          11359649          24229338   2.24
..                          ...               ...               ...    ...
189                    30.26050          60123739          38063117   1.04
190                         NaN           1145354           3898258   1.75
191                     0.00000          20491585          13205029   1.27
192                    15.06020          10857387           9160288   2.15
193                    30.56600          11033499           5287038   1.85

     democracy_score  democracy_type  median_age       political_leader  \
0               2.97   Authoritarian        12.9           Ashraf Ghani
1               5.98   Hybrid regime        33.7               Edi Rama
2               3.50   Authoritarian        24.0   Abdelmadjid Tebboune
3               0.00         Unknown        38.9    Xavier Espot Zamora
4               3.62   Authoritarian        12.4          João Lourenço
..               ...             ...         ...                    ...
189             3.08   Authoritarian        28.4       Nguyễn Phú Trọng
190             4.39   Hybrid regime        15.4                    NaN
191             1.95   Authoritarian        14.8  Abdrabbuh Mansur Hadi
192             5.61   Hybrid regime        13.2            Edgar Lungu
193             3.16   Authoritarian        14.2     Emmerson Mnangagwa

                                        title
0                                   President
1                              Prime Minister
2                                   President
3                          Head of Government
4                                   President
..                                        ...
189  General Secretary of the Communist Party
190                                       NaN
191                                 President
192                                 President
193                                 President

[194 rows x 64 columns]>

In [ ]:
# WHICH COUUNTRY HAVE HIGHEST POPULATION

In [10]:
df[df["population"] == df["population"].max()]["country"]

75    India
Name: country, dtype: object

In [ ]:
#WHAT IS CAPITAL OF COUNTRY WITH HIGHEST POPULATION

In [11]:
df[df["population"]== df["population"].max()]["capital_city"]

75    New Delhi
Name: capital_city, dtype: object

In [ ]:
#WHICH COUNTRY HAVE LEAST POPULATION

In [12]:
df[df["population"] == df["population"].min()]["country"]

179    Tuvalu
Name: country, dtype: object

In [ ]:
#CAPITAL OF COUNTRY WITH LEAST POPULATION

In [17]:

df[df["population"]== df["population"].min()]["capital_city"]

179    Funafuti
Name: capital_city, dtype: object

In [ ]:
#TOP 5 COUNTRIES WITH HIGHEST DEMOCRATIC SCORE

In [28]:
df.sort_values(by="democracy_score", ascending=False, inplace=True)

In [27]:
df.head()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.0,65.0,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.0,20.0,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.0,3.0,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.5,1.5,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.5,18.5,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President

In [29]:
df["country"].head()

127         Norway
74         Iceland
164         Sweden
122    New Zealand
46         Denmark
Name: country, dtype: object

In [ ]:
#HOW MANY TOTAL REGIONS

In [33]:
df["region"].value_counts().count()

np.int64(22)

In [ ]:
#HOW  MANY COUNTRIES LIE IN EASTERN EUROPE REGION

In [36]:
df[df["region"] =="Eastern Europe"]["country"]

43      Czech Republic
151    Slovak Republic
24            Bulgaria
136             Poland
73             Hungary
139            Romania
111            Moldova
181            Ukraine
14             Belarus
140             Russia
Name: country, dtype: object

In [ ]:
#POLITICAL LEADER OF 2ND HIGHEST POPULATED COUNTRY

In [38]:
df[df["population"]==df["population"].nlargest(2).iloc[1]]["political_leader"]

34    Xi Jinping
Name: political_leader, dtype: object

In [ ]:
#HOW MANY COUNTRIES ARE THERE WHOSE POLITICAL LEADER ARE UNKNOWN

In [40]:
df.loc[df["political_leader"].isna()]["country"]

27                         Cabo Verde
172                       Timor-Leste
151                   Slovak Republic
190                West Bank and Gaza
161    St. Vincent and the Grenadines
160                         St. Lucia
159               St. Kitts and Nevis
Name: country, dtype: object

In [ ]:
#HOW MANY COUNTRY HAVE REPUBLIC IN THEIR FULL NAME

In [41]:
count = df[df["country_long"].str.contains("Republic", case=False)].shape[0]

print(count)

125

In [43]:
countries = df[df["country_long"].str.contains("Republic", case=False)]["country_long"].unique()

print(countries)

['Republic of Iceland' 'Republic of Finland' 'Federal Republic of Germany'
 'Oriental Republic of Uruguay' 'Republic of Austria'
 'Republic of Mauritius' 'Republic of Malta' 'Republic of Costa Rica'
 'Republic of Korea' 'Republic of Estonia' 'Republic of Chile'
 'Republic of Cabo Verde' 'Portuguese Republic' 'Republic of Botswana'
 'French Republic' 'Italian Republic' 'Czech Republic'
 'Republic of Cyprus' 'Republic of Slovenia' 'Republic of Lithuania'
 'Republic of Latvia' 'Hellenic Republic' 'Republic of South Africa'
 'Republic of India' 'Democratic Republic of Timor-Leste'
 'Republic of Trinidad and Tobago' 'Slovak Republic' 'Republic of Panama'
 'Republic of Bulgaria' 'Argentine Republic' 'Republic of Suriname'
 'Federative Republic of Brazil' 'Republic of Colombia'
 'Republic of the Philippines' 'Co-operative Republic of Guyana'
 'Republic of Poland' 'Republic of Ghana' 'Republic of Peru'
 'Republic of Croatia' 'Dominican Republic' 'Republic of Tunisia'
 'Republic of Serbia' 'Republic of Indonesia' 'Republic of Singapore'
 'Republic of Ecuador' 'Republic of Namibia' 'Republic of Paraguay'
 'Democratic Socialist Republic of Sri Lanka' 'Republic of Senegal'
 'Republic of Albania' 'Republic of El Salvador'
 'Republic of North Macedonia' 'Republic of Moldova' 'Republic of Fiji'
 'Republic of Benin' 'Republic of Honduras' 'Republic of Zambia'
 'Republic of Guatemala' "People's Republic of Bangladesh"
 'Republic of Malawi' 'Republic of Mali' 'United Republic of Tanzania'
 'Republic of Liberia' 'Republic of Madagascar' 'Republic of Uganda'
 'Kyrgyz Republic' 'Republic of Kenya' 'Republic of Haiti'
 'Republic of Armenia' 'Republic of Sierra Leone' 'Lebanese Republic'
 'Federal Republic of Nigeria' 'Republic of Turkey'
 'Republic of The Gambia' 'Islamic Republic of Pakistan'
 "Republic of Côte d'Ivoire" 'Republic of Iraq' 'Republic of Mozambique'
 'Republic of the Union of Myanmar' 'Islamic Republic of Mauritania'
 'Republic of Niger' 'Republic of Nicaragua' "People's Republic of Angola"
 'Gabonese Republic' "People's Democratic Republic of Algeria"
 'Arab Republic of Egypt' 'Federal Democratic Republic of Ethiopia'
 'Republic of Rwanda' "People's Republic of China" 'Republic of Congo'
 'Republic of Cameroon' 'Republic of Zimbabwe' 'Republic of Guinea'
 'Republic of Belarus' 'Republic of Togo' 'Socialist Republic of Vietnam'
 'Republic of Cuba' 'Republic of Kazakhstan' 'Republic of Djibouti'
 'Republic of Azerbaijan' 'Islamic Republic of Iran'
 "Lao People's Democratic Republic" 'Republic of Burundi'
 'Republic of the Sudan' 'Republic of Uzbekistan'
 'Republic of Guinea-Bissau' 'Republic of Yemen' 'Republic of Tajikistan'
 'Republic of Equatorial Guinea' 'Republic of Chad'
 'Central African Republic' 'Democratic Republic of the Congo'
 'Syrian Arab Republic' "Democratic People's Republic of Korea"
 'Republic of Palau' 'Republic of Vanuatu'
 'Democratic Republic of São Tomé and Principe' 'Republic of Nauru'
 'Republic of Seychelles' 'Republic of San Marino'
 'Republic of South Sudan' 'Republic of Kiribati'
 'Republic of the Marshall Islands' 'Republic of Maldives'
 'Somali Democratic Republic']

In [ ]:
# WHICH COUNTRY IN AFRICAN REGION HAS HIGHEST POPULATION

In [45]:
africa_df=df[df["continent"] == 'Africa']

In [48]:
africa_df[africa_df["population"] == africa_df["population"].max()]["country"]

125    Nigeria
Name: country, dtype: object